# Generated by Django 3.1.3 on 2021-10-23 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
