# Generated by Django 3.1.3 on 2021-10-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_supplier_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('continent', models.CharField(choices=[('ASIA', 'ASIA'), ('EUROPE', 'EUROPE'), ('AFRICA', 'AFRICA'), ('N.AMERICA', 'N.AMERICA'), ('S.AMERICA', 'S.AMERICA'), ('AUSTRALIA', 'AUSTRALIA')], max_length=100)),
            ],
        ),
    ]
