# Generated by Django 3.1.3 on 2021-10-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField()),
                ('re_order_level', models.FloatField(default=0)),
                ('receive_amount', models.FloatField(default=0)),
                ('sell_amount', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.supplier')),
            ],
        ),
    ]
