# Generated by Django 3.1.3 on 2021-10-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_reported', models.DateField(auto_now=True)),
            ],
        ),
    ]
