# Generated by Django 3.2.8 on 2021-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
    ]
