# Generated by Django 3.2.8 on 2021-10-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_stock_discount_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stocks',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='stock',
            new_name='item',
        ),
    ]
